name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-2022  # (Windows-2022 is the closest option for Windows 10)

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      # Step 3: Set up Maven
      - name: Set up Maven
        uses: actions/setup-maven@v2

      # Step 4: Build and run the tests
      - name: Run JUnit tests
        run: mvn clean test
        working-directory: ./
