name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-2022  # (Windows-2022 is the closest option for Windows 10)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          architecture: x64
          cache: maven

      - name: Run JUnit tests
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ./
